include = ["Low Profile/*.swift", "Low Profile/**/*.swift", "Low Profile Tests/*.swift"]
align-after-colon = ["parameters", "throws", "returns"]
parameter-style = "grouped"
needs-separation = ["description", "parameters", "throws"]
vertical-align = true
